/**
 * @file    autoconfig.h
 * @date    2020-10-04
 * @brief   This file is auto generated by CMake
 *
 */

#ifndef __AUTO_CONFIG_H__
#define __AUTO_CONFIG_H__

#ifndef _DEBUG
#define _DEBUG
#endif /* _DEBUG */

#ifndef DEBUG
#define DEBUG
#endif /* DEBUG */

#ifndef STM32F303xE
#define STM32F303xE
#endif /* STM32F303xE */

#ifndef SIGNATURE
#define SIGNATURE "Hello World!"
#endif /* SIGNATURE */

#ifndef AUTO_CONFIG_VER
#define AUTO_CONFIG_VER 6.672
#endif /* AUTO_CONFIG_VER */

#ifndef CHEAT
#define CHEAT "Show Me The Money!"
#endif /* CHEAT */

#endif /* __AUTO_CONFIG_H__ */
