/**
 * @file    autoconfig.h
 * @date    2020-10-12
 * @brief   This file is auto generated by CMake
 *
 */

#ifndef __AUTO_CONFIG_H__
#define __AUTO_CONFIG_H__

#ifndef _DEBUG
#define _DEBUG
#endif /* _DEBUG */

#ifndef DEBUG
#define DEBUG
#endif /* DEBUG */

#ifndef STM32F303xE
#define STM32F303xE
#endif /* STM32F303xE */

#endif /* __AUTO_CONFIG_H__ */
